// Code generated by scripts/generate-builtins.php — DO NOT EDIT.
// Source: hand-seeded with ~50 high-impact PHP 8.x additions pending full
// phpstorm-stubs generation. See BUILTIN_STUBS_PLAN.md.

package symbols

var generatedBuiltinAvailability = map[string]BuiltinAvailability{
	// PHP 8.0 — class-likes / attributes
	"Attribute":           {Since: "8.0"},
	"ReflectionUnionType": {Since: "8.0"},
	"Stringable":          {Since: "8.0"},
	"WeakMap":             {Since: "8.0"},

	// PHP 8.0 — functions
	"fdiv":                {Since: "8.0"},
	"get_debug_type":      {Since: "8.0"},
	"get_resource_id":     {Since: "8.0"},
	"preg_last_error_msg": {Since: "8.0"},
	"str_contains":        {Since: "8.0"},
	"str_ends_with":       {Since: "8.0"},
	"str_starts_with":     {Since: "8.0"},

	// PHP 8.1 — class-likes / attributes
	"AllowDynamicProperties":     {Since: "8.1"},
	"BackedEnum":                 {Since: "8.1"},
	"Fiber":                      {Since: "8.1"},
	"ReflectionEnum":             {Since: "8.1"},
	"ReflectionEnumBackedCase":   {Since: "8.1"},
	"ReflectionEnumUnitCase":     {Since: "8.1"},
	"ReflectionFiber":            {Since: "8.1"},
	"ReflectionIntersectionType": {Since: "8.1"},
	"ReturnTypeWillChange":       {Since: "8.1"},
	"UnitEnum":                   {Since: "8.1"},

	// PHP 8.1 — functions
	"array_is_list": {Since: "8.1"},
	"enum_exists":   {Since: "8.1"},
	"fdatasync":     {Since: "8.1"},
	"fsync":         {Since: "8.1"},

	// PHP 8.2 — class-likes / attributes
	"SensitiveParameter":      {Since: "8.2"},
	"SensitiveParameterValue": {Since: "8.2"},

	// PHP 8.2 — functions
	"mb_str_pad":                {Since: "8.2"},
	"openssl_cipher_key_length": {Since: "8.2"},

	// PHP 8.3 — class-likes / attributes
	"Override": {Since: "8.3"},

	// PHP 8.3 — functions
	"json_validate": {Since: "8.3", Extension: "json"},
	"str_decrement": {Since: "8.3"},
	"str_increment": {Since: "8.3"},

	// PHP 8.4 — class-likes / attributes
	"Deprecated": {Since: "8.4"},

	// PHP 8.4 — functions
	"array_all":      {Since: "8.4"},
	"array_any":      {Since: "8.4"},
	"array_find":     {Since: "8.4"},
	"array_find_key": {Since: "8.4"},
	"mb_lcfirst":     {Since: "8.4"},
	"mb_ltrim":       {Since: "8.4"},
	"mb_rtrim":       {Since: "8.4"},
	"mb_trim":        {Since: "8.4"},
	"mb_ucfirst":     {Since: "8.4"},
}
